chore: Try java-version 21?
When java-version contains just a number, it installs the latest available version.

17.0.10 *is* the latest available version for 17!

Thus, trying to install 17.0.17 results in a failure:

    Error: Could not find satisfied version for SemVer 17.0.17.
    Available versions: 25.0.0, 21.0.2, 21.0.1, 21.0.0, 17.0.10, 17.0.9, 17.0.8, 17.0.8.1, 17.0.7, 17.0.6, 17.0.5, 17.0.4, 17.0.3, 17.0.1+12.1, 16.0.2+7.1, 11.0.19, 11.0.18, 11.0.17, 11.0.16, 11.0.15, 11.0.13+8.1

As uno-check is looking for 17.0.17, and the Linux bot doesn't have
that, what if we provision JDK *21*?

JDK 21 is supported by .NET for Android, and is later than 17.0.16,
so hopefully this will pass `uno-check`?