chore: provision Microsoft OpenJDK 17 on Linux
Context: https://github.com/unoplatform/uno.check/pull/474
Context: https://github.com/unoplatform/uno.check/actions/runs/19286859335/job/55149509651?pr=474

The **Validate Tool - Linux - Preview** stage is failing, with log
output containing:

	› OpenJDK 17.0.16 Checkup...
	…
	ValidateJavaSdkLocation: `/opt/hostedtoolcache/Java_Microsoft_jdk/11.0.19/x64`, result=True
	…
	SHELL: /bin/bash /tmp/tmpt18XKD.tmp
	javac 17.0.17
	  – 11.0.19 (/opt/hostedtoolcache/Java_Microsoft_jdk/11.0.19/x64)
	  – 17.0.17 (/usr/lib/jvm/temurin-17-jdk-amd64)
	SetEnvironmentVariable: LATEST_JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64

	────────────────────────────────────────────────────────────────────────────────
	¤ Recommendation: Install OpenJDK17
	OpenJDK 17 is missing, follow the installation instructions here:
	https://learn.microsoft.com/en-us/java/openjdk/install#install-on-ubuntu
	────────────────────────────────────────────────────────────────────────────────
	…
	────────────────────────────────────────────────────────────────────────────────

	Checkup had Error status: openjdk

	openjdk:
	! There were one or more problems detected.
	Please review the errors and correct them and run uno-check again.
	Has Errors? True
	Error: Process completed with exit code 1.

The problem is that:

 1. The test provisions Microsoft OpenJDK *11*
 2. `uno-check` is now requiring Microsoft OpenJDK *17*.
 3. `uno-check` doesn't support looking for any other JDK.
 4. `uno-check` cannot install Microsoft OpenJDK on Linux; it can
    only request that the user install it manually, hence the message:

        follow the installation instructions here:
        https://learn.microsoft.com/en-us/java/openjdk/install#install-on-ubuntu

@jeromelaban [said][0]:

> Since uno-check does not install it, it might only be that the CI
> test on linux should have that version installed prior to running
> uno-check.

Do that: update `ci.yml` to provision Microsoft OpenJDK 17.
This should allow the tests to pass.

[0]: https://github.com/unoplatform/uno.check/pull/474#issuecomment-3519749003