fix(manifest): Bump SDK to include Xcode15 vs NewsstandKit fix
With this newer SDK there's a workaround for the issue.

Before
```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7098/targets/Xamarin.Shared.Sdk.targets(1139,3): error : clang exited with code 1: [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7098/targets/Xamarin.Shared.Sdk.targets(1139,3): error : In file included from /Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/obj/Debug/net7.0-ios/iossimulator-x64/linker-cache/registrar.mm:3: [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7098/targets/Xamarin.Shared.Sdk.targets(1139,3): error : /Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/obj/Debug/net7.0-ios/iossimulator-x64/linker-cache/registrar.h:34:9: fatal error: 'NewsstandKit/NewsstandKit.h' file not found [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7098/targets/Xamarin.Shared.Sdk.targets(1139,3): error : #import <NewsstandKit/NewsstandKit.h> [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7098/targets/Xamarin.Shared.Sdk.targets(1139,3): error :         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7098/targets/Xamarin.Shared.Sdk.targets(1139,3): error : 1 error generated. [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
```

After
```
ILLINK : warning MT4178: The class 'NewsstandKit.NKAssetDownload' will not be registered because the NewsstandKit framework has been removed from the iOS SDK. [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
ILLINK : warning MT4178: The class 'NewsstandKit.NKLibrary' will not be registered because the NewsstandKit framework has been removed from the iOS SDK. [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
ILLINK : warning MT4189: The class 'PassKit.PKDisbursementAuthorizationControllerDelegate' will not be registered it has been removed from the iOS SDK. [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
ILLINK : warning MT4178: The class 'NewsstandKit.NKIssue' will not be registered because the NewsstandKit framework has been removed from the iOS SDK. [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
ILLINK : warning MT4189: The class 'PassKit.PKDisbursementAuthorizationController' will not be registered it has been removed from the iOS SDK. [/Users/poupou/git/spouliot/templates/uno/4.9.0-dev.164/unoapp/unoapp.Mobile/unoapp.Mobile.csproj::TargetFramework=net7.0-ios]
```